<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net47</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>LB_Mod_Installer</RootNamespace>
    <AssemblyName>LB Mod Installer</AssemblyName>
    <ApplicationIcon>Resources\DBXV2_101.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ControlzEx" Version="4.4.0" />
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ini-parser-netstandard" Version="2.5.3" />
    <PackageReference Include="MahApps.Metro" Version="2.4.9" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialLight" Version="4.11.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="YAXLib">
      <HintPath>..\DLLs\YAXLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <Compile Include="Binding\AliasValue.cs" />
    <Compile Include="Binding\AutoIdContext.cs" />
    <Compile Include="Binding\BindingManager.cs" />
    <Compile Include="Binding\BindingValue.cs" />
    <Compile Include="Binding\X2MHelper.cs" />
    <Compile Include="Binding\ZipImageConverter.cs" />
    <Compile Include="Binding\XML\XmlParser.cs" />
    <Compile Include="Binding\XML\ZipReaderExtensions.cs" />
    <Compile Include="File\FileCacheManager.cs" />
    <Compile Include="Installer\Install.cs" />
    <Compile Include="Installer\InstallHelpers.cs" />
    <Compile Include="Installer\LocaleResource.cs" />
    <Compile Include="Installer\MsgComponentInstall.cs" />
    <Compile Include="Installer\OptionModuleImporter.cs" />
    <Compile Include="Installer\ProgressEta.cs" />
    <Compile Include="Installer\ACB\AcbInstaller.cs" />
    <Compile Include="Installer\ACB\AcbUninstaller.cs" />
    <Compile Include="Installer\Uninstall.cs" />
    <Compile Include="Tracking\GameDir.cs" />
    <Compile Include="Tracking\SavedSelectedOptions.cs" />
    <Compile Include="Tracking\Sections.cs" />
    <Page Include="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Compile Include="App.xaml.cs">
      <DependentUpon>App.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="GeneralInfo.cs" />
    <Compile Include="Installer\InstallerXml.cs" />
    <Compile Include="Tracking\TrackingXml.cs" />
    <Compile Include="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\silence.hca" />
  </ItemGroup>
</Project>
