<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>AudioCueEditor</RootNamespace>
    <AssemblyName>ACE</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <LangVersion>9</LangVersion>
    <StartupObject>AudioCueEditor.App</StartupObject>
		<Nullable>disable</Nullable>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<PublishSingleFile>true</PublishSingleFile>
    <LangVersion>14</LangVersion>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ControlzEx" Version="4.4.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialLight" Version="4.11.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="4.11.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="4.11.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
    <PackageReference Include="NAudio" Version="2.4.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>
	
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<Reference Include="AutoUpdater">
      <HintPath>..\DLLs\net10\AutoUpdater.dll</HintPath>
    </Reference>
    <Reference Include="YAXLib">
      <HintPath>..\DLLs\net10\YAXLib.dll</HintPath>
    </Reference>
	</ItemGroup>
	
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<Reference Include="AutoUpdater">
      <HintPath>..\DLLs\AutoUpdater.dll</HintPath>
    </Reference>
    <Reference Include="YAXLib">
      <HintPath>..\DLLs\YAXLib.dll</HintPath>
    </Reference>
  
		<Reference Include="PresentationFramework.Aero" />
    <Reference Include="System.IO.Compression" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\LB_Common\LB_Common.csproj" />
    <ProjectReference Include="..\Xv2CoreLib\Xv2CoreLib.csproj" />
  </ItemGroup>
	
	<!-- Automated publish on release build. Merges all assemblies into one executable for .NET 10 (as Fody.Costura is not sufficent) -->
	<!-- Release ready builds in {Configuration}/[TargetFramework}/{Platform} -->
	<Target Name="SetNoBuild" Condition="'$(Configuration)' == 'Release'">
		<PropertyGroup>
			<NoBuild>true</NoBuild>
		</PropertyGroup>
	</Target>
	<Target Name="PublishAfterBuild" AfterTargets="AfterBuild" DependsOnTargets="SetNoBuild;Publish" Condition="'$(Configuration)' == 'Release'" />
	<Target Name="CleanAfterBuild" AfterTargets="AfterClean" Condition="'$(Configuration)' == 'Release'">
		<RemoveDir Directories="$(PublishDir)" Condition="'$(PublishDir)' != ''" />
	</Target>
</Project>
